#!/usr/bin/env bash
#
# Add a facility: database, media directory, environment, service, vhost.
#
#     sudo ./provision-facility.sh zmb "Center for Microscopy and Image Analysis" admin@zmb.uzh.ch
#
# What this does NOT do, deliberately: install the software. The software is
# already there — one release directory, one virtualenv, shared by every
# facility. A facility is a database, a media directory, an environment file
# and a subdomain. Adding one copies no code.
#
# Author: Thom de Hoog <thom.dehoog@zmb.uzh.ch>, <thomdehoog@gmail.com>

set -euo pipefail

SLUG="${1:-}"
NAME="${2:-}"
ADMIN_EMAIL="${3:-}"
DOMAIN="${RETICLE_DOMAIN:-reticle.ch}"
ROOT="${RETICLE_ROOT:-/opt/reticle}"
DB_HOST="${RETICLE_DB_HOST:-localhost}"
DB_ADMIN="${RETICLE_DB_ADMIN:-postgres}"

if [[ -z "$SLUG" || -z "$NAME" || -z "$ADMIN_EMAIL" ]]; then
    echo "usage: $0 <slug> <display name> <admin email>" >&2
    echo "   eg: $0 zmb 'Center for Microscopy and Image Analysis' admin@zmb.uzh.ch" >&2
    exit 64
fi

# The slug becomes a subdomain, a database name, a systemd instance and a
# directory. Validating it once here is cheaper than discovering which of those
# four rejects a space.
if [[ ! "$SLUG" =~ ^[a-z][a-z0-9-]{1,30}$ ]]; then
    echo "Refusing '$SLUG': use lower-case letters, digits and hyphens, starting with a letter." >&2
    exit 64
fi

FACILITY_DIR="$ROOT/facilities/$SLUG"
if [[ -e "$FACILITY_DIR" ]]; then
    echo "Refusing: $FACILITY_DIR already exists. Remove it deliberately if you mean to start over." >&2
    exit 65
fi

# Ports are derived from a base so two facilities cannot collide, and recorded
# in the environment file so nothing has to recompute it later.
# Taken from the env files rather than from what is listening: a facility that
# is merely stopped still owns its port, and handing it to a new facility means
# the older one fails the next time it starts.
BASE_PORT="${RETICLE_BASE_PORT:-8000}"
PORT=$BASE_PORT
while grep -rqs "^RETICLE_PORT='\?$PORT'\?$" "$ROOT"/facilities/*/env \
   || ss -ltn "sport = :$PORT" 2>/dev/null | grep -q LISTEN; do
    PORT=$((PORT + 1))
done

echo "==> Facility '$SLUG' at ${SLUG}.${DOMAIN} on port $PORT"

# --- 1. the database -------------------------------------------------------
# One per facility. This is the isolation decision: a query that forgets its
# filter cannot reach another facility's data, because the connection does not
# contain it.
DB_NAME="reticle_${SLUG//-/_}"
DB_USER="reticle_${SLUG//-/_}"
DB_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"

echo "==> Creating database $DB_NAME"
sudo -u "$DB_ADMIN" psql -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD';
CREATE DATABASE $DB_NAME OWNER $DB_USER ENCODING 'UTF8';
-- No rights on anything else. The role can reach its own database and nothing
-- more, which is the second half of the isolation the separate database buys.
REVOKE ALL ON DATABASE $DB_NAME FROM PUBLIC;
SQL

# --- 2. the directories ----------------------------------------------------
install -d -o reticle -g reticle -m 750 "$FACILITY_DIR"
install -d -o reticle -g reticle -m 750 "$FACILITY_DIR/media"
install -d -o reticle -g reticle -m 750 "$FACILITY_DIR/backups"

# --- 3. the environment ----------------------------------------------------
# The secret key is per facility on purpose. It is the pepper for session-token
# digests, so sharing one would mean a stolen database from one facility could
# be used to forge sessions at another.
SECRET_KEY="$(openssl rand -base64 48 | tr -d '\n')"

# A single quote inside a single-quoted shell value ends the quoting. Replacing
# each one with '\'' closes, escapes and reopens - the standard idiom, and the
# reason a name like "St John's Imaging" does not break the file.
SAFE_NAME=${NAME//\'/\'\\\'\'}
SAFE_EMAIL=${ADMIN_EMAIL//\'/\'\\\'\'}
ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"

(umask 077; cat > "$FACILITY_DIR/env" <<ENV
# Generated by provision-facility.sh for $SLUG. Facility-specific settings only;
# anything shared belongs in the code, not here.
# Every value is single-quoted. This file is read by systemd AND sourced by
# bash during provisioning, and an unquoted value containing a space makes bash
# read the rest of the line as a command - so a plain multi-word facility name
# silently produced an empty variable, and a value containing a command
# substitution would have been executed.
RETICLE_SECRET_KEY='$SECRET_KEY'
RETICLE_DATABASE_URL='postgresql+psycopg://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME'
RETICLE_MEDIA_ROOT='$FACILITY_DIR/media'
RETICLE_PORT='$PORT'

RETICLE_ORGANISATION_NAME='$SAFE_NAME'
RETICLE_ORGANISATION_SHORT_NAME='${SLUG^^}'
RETICLE_ORGANISATION_URL='https://${SLUG}.${DOMAIN}'

RETICLE_COOKIE_SECURE=true
RETICLE_LOG_LEVEL=INFO

# Same-origin in production: nginx serves the pages and /api under one
# hostname, so CORS never comes into play.
RETICLE_CORS_ORIGINS='https://${SLUG}.${DOMAIN}'

RETICLE_ADMIN_EMAIL='$SAFE_EMAIL'
RETICLE_ADMIN_PASSWORD='$ADMIN_PASSWORD'
ENV
)
chown reticle:reticle "$FACILITY_DIR/env"

# --- 4. schema and first account ------------------------------------------
echo "==> Migrating"
sudo -u reticle bash -c "set -a; . '$FACILITY_DIR/env'; set +a; cd '$ROOT/current/backend' && '$ROOT/current/venv/bin/alembic' upgrade head"

echo "==> Seeding the first administrator"
sudo -u reticle bash -c "set -a; . '$FACILITY_DIR/env'; set +a; cd '$ROOT/current/backend' && '$ROOT/current/venv/bin/python' -m app.seed"

# The bootstrap password exists to be used once and replaced. Removing it from
# the environment file means it is not sitting on disk after first sign-in, and
# `app.seed` is idempotent so its absence changes nothing on later runs.
sed -i '/^RETICLE_ADMIN_PASSWORD=/d' "$FACILITY_DIR/env"

# --- 5. the service --------------------------------------------------------
echo "==> Starting reticle@$SLUG"
systemctl enable --now "reticle@$SLUG"

for _ in $(seq 1 30); do
    if curl -sf "http://127.0.0.1:$PORT/api/ready" >/dev/null; then break; fi
    sleep 2
done
curl -sf "http://127.0.0.1:$PORT/api/ready" >/dev/null || {
    echo "The service started but never became ready. Check: journalctl -u reticle@$SLUG" >&2
    exit 70
}

# --- 6. the vhost ----------------------------------------------------------
sed -e "s/{{SLUG}}/$SLUG/g" -e "s/{{DOMAIN}}/$DOMAIN/g" -e "s/{{PORT}}/$PORT/g" \
    "$(dirname "$0")/nginx-facility.conf.template" > "/etc/nginx/sites-available/reticle-$SLUG"
ln -sfn "/etc/nginx/sites-available/reticle-$SLUG" "/etc/nginx/sites-enabled/reticle-$SLUG"
nginx -t && systemctl reload nginx

cat <<DONE

    Facility '$SLUG' is up.

      URL        https://${SLUG}.${DOMAIN}
      Admin      $ADMIN_EMAIL
      Password   $ADMIN_PASSWORD

    Give that password to the administrator by a route that is not email, and
    tell them to change it at first sign-in. It has already been removed from
    the environment file, so this is the only place it appears.

    Still to do by hand:
      - DNS: point ${SLUG}.${DOMAIN} at this host (or use a wildcard record).
      - TLS: certbot --nginx -d ${SLUG}.${DOMAIN}, unless a wildcard
        certificate for *.${DOMAIN} is already installed.

DONE
